### ISSUE TITLE
Allow collection without specifying job name, pipeline name or team name

### ISSUE THREAD

**Issue by jchesterpivotal** [jchesterpivotal/concourse-build-resource#6]
## The problem

In the current design, a user fully specifies the team, pipeline and job they wish to follow:

```yaml
- name: build
  type: concourse-build
  source:
    concourse_url: https://concourse.example.com
    team: main
    pipeline: example-pipeline
    job: some-job-you-are-interested-in
```

This is good if I want to just follow a single job. But it is a hassle when scaling up for two reasons.

1. Repetition. If I am following twenty jobs, I need to create a resource for every job. But these resources will have repeated configuration for URL, team and pipeline. This is unwieldy in terms of YAML and also, means I am spamming Concourse with 20 check containers instead of a single check container.

2. Dynamism. If I want to keep my scraping up to date, I will need to manually reconcile my scraping pipeline with target jobs. If a job is added on the target system, it does not get watched automatically. If the job is removed, my pipeline breaks.

## A solution

Under the hood this resource uses `go-concourse` to interact with Concourse. Based on an eyeball inspection, it will be possible to loosen the restriction, so that one can track jobs to an arbitrary level of the hierarchy.

Afterwards, these would all be legal configurations:

```yaml
# Track builds of a single job in single pipeline in single team
- name: build
  type: concourse-build
  source:
    concourse_url: https://concourse.example.com
    team: main
    pipeline: example-pipeline
    job: some-job-you-are-interested-in
```

```yaml
# Track builds of all jobs in a single pipeline in a single team
- name: build
  type: concourse-build
  source:
    concourse_url: https://concourse.example.com
    team: main
    pipeline: example-pipeline
```

```yaml
# Track builds of all jobs in all pipelines in a single team
- name: build
  type: concourse-build
  source:
    concourse_url: https://concourse.example.com
    team: main
```

```yaml
# Track builds of all jobs in all pipelines in all teams (ie, track everything)
- name: build
  type: concourse-build
  source:
    concourse_url: https://concourse.example.com
```

## Todos

* [x] Jobs in pipeline
  * [x] cmd/check
  * [x] pkg/check
* [x] Jobs in pipelines in team
  * [x] cmd/check
  * [x] pkg/check
* [x] Jobs in pipelines in teams
  * [x] cmd/check
  * [x] pkg/check
* [x] Add metadata to pkg/in response to more easily distinguish job builds in resource view
